# NOTE: To see a full config with all available options:
# noctalia config export full > noctalia-full-config.toml

[theme]
builtin = "Catppuccin"
mode = "dark"
source = "builtin"
    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.5
    padding = 10
    radius = 0
    margin_edge = 0
    margin_ends = 0
    margin_opposite_edge = 0
    widget_spacing = 12

    start = [ "launcher", "workspaces", "spacer", "spacer", "taskbar" ]
    center = [ "clock" ]
    end = [
        "tray",
        "clipboard",
        "cpu",
        "ram",
        "network",
        "bluetooth",
        "volume",
        "brightness",
        "battery",
        "control-center",
        "session"
    ]
        [bar.default.dead_zone.actions]
        scroll_down = "exec niri msg action focus-workspace-down"
        scroll_up = "exec niri msg action focus-workspace-up"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 1800.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 3600.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 900.0

[osd]
    [osd.kinds]
    media = false

[wallpaper]
enabled = true
directory = "~/Pictures/wallpaper"
transition_on_startup = true

    [wallpaper.automation]
    enabled = true
    interval_seconds = 1800
    order = "random"
    recursive = true

[nightlight]
enabled = true
force = true
temperature_day = 6500
temperature_night = 4000

[shell]
font_family = "Lilex Nerd Font"
time_format = "{:%-I:%M %p} | {:%Y-%m-%d}"
clipboard_enabled = false

[widget.clock]
format = "{:%-I:%M %p} // {:%Y-%m-%d}"

[widget.cpu]
display = "text"

[widget.ram]
display = "text"
