# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
# [character] # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[buf]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[rust]
symbol = " "

[aws]
symbol = "  "
style = "bold #ffb86c"

[character]
error_symbol = "[λ](bold #ff5555)"
success_symbol = "[λ](bold #f8f8f2)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
read_only = " "
style = "bold #50fa7b"

[git_branch]
symbol = " "
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #ff5555"

[username]
format = "[$user]($style) on "
style_user = "bold #bd93f9"
